#!/bin/bash

file="/etc/crontab.backup"
cron=$(md5sum /etc/crontab | cut -d' ' -f1)
if [ -f "$file" ]
	then
		file=$(cat /etc/crontab.backup)
	else
		file="$cron"
	fi
	if [ "$file" != "$cron" ]
	then
	    echo "file modified" | mail -s "/etc/crontab has been modified" root
	fi
md5sum /etc/crontab | cut -d ' ' -f1 > /etc/crontab.backup

# in command line: crontab -e, select option 1
# one a new line in the file: '0 0 * * 0-6 /path/to/file
